package com.example.PlantsAndFriends;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "plants")
public class PlantEntity {
    @PrimaryKey(autoGenerate = true)
    // id autogenerated by firestore
    private int id;
    // this is the plant identification for the local storage, which is used to identify the plant on firestore
    private String number;
    private String name;
    private String species;
    private float min_temp;
    private float max_temp;
    private float min_humidity;
    private float max_humidity;
    private String description;
    private String imgUri;

    public PlantEntity() {
    }

    // getters and setters

    // Getter for id
    public int getId() {
        return id;
    }

    // Setter for id
    public void setId(int id) {
        this.id = id;
    }

    // Getter for number
    public String getNumber() {
        return number;
    }

    // Setter for number
    public void setNumber(String number) {
        this.number = number;
    }

    // Getter for title
    public String getName() {
        return name;
    }

    // Setter for title
    public void setName(String name) {
        this.name = name;
    }

    // Getter for species
    public String getSpecies() {
        return species;
    }

    // Setter for species
    public void setSpecies(String species) {
        this.species = species;
    }

    // Getter for min temperature
    public float getMin_temp() {
        return min_temp;
    }

    // Setter for min temperature
    public void setMin_temp(float min_temp) {
        this.min_temp = min_temp;
    }

    // Getter for max temperature
    public float getMax_temp() {
        return max_temp;
    }

    // Setter for max temperature
    public void setMax_temp(float max_temp) {
        this.max_temp = max_temp;
    }

    // Getter for min humidity
    public float getMin_humidity() {
        return min_humidity;
    }

    // Setter for min humidity
    public void setMin_humidity(float min_humidity) {
        this.min_humidity = min_humidity;
    }

    // Getter for max humidity
    public float getMax_humidity() {
        return max_humidity;
    }

    // Setter for max humidity
    public void setMax_humidity(float max_humidity) {
        this.max_humidity = max_humidity;
    }

    // Getter for content
    public String getDescription() {
        return description;
    }

    // Setter for content
    public void setDescription(String description) {
        this.description = description;
    }

    // Getter for image url
    public String getImgUri() {
        return imgUri;
    }

    // Setter for image url
    public void setImgUri(String imgUri) {
        this.imgUri = imgUri;
    }

}
